// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvkfhprjpegjyzktyueh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2a2ZocHJqcGVnanl6a3R5dWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTc1NDcsImV4cCI6MjA2NTUzMzU0N30.0cWB9FAbhO-vHUt_th6yGGLVW0jSF08qBpRilZsSOd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);