/**
 * Module configuration constants
 */

import {
  BarChart3,
  CalendarCheck,
  DollarSign,
  GraduationCap,
  LayoutDashboard,
  Package,
  Settings,
  Users,
} from "lucide-react";
import type { ModuleConfig } from "../types/permissions";

export const ROLE_MODULES: ModuleConfig[] = [
  {
    id: "workspace",
    label: "Workspace Essentials",
    description: "Dashboard, messaging, tasks, and goal tracking.",
    icon: LayoutDashboard,
    permissions: ["viewOwnProfile", "viewOwnTasks", "viewTeamTasks"],
    sections: ["dashboard", "messages", "tasks", "goals"],
    defaults: {
      owner: true,
      admin: true,
      manager: true,
      supervisor: true,
      staff: true,
    },
    risk: "low",
  },
  {
    id: "team",
    label: "Team Visibility",
    description: "Directory, position management, and user oversight.",
    icon: Users,
    permissions: [
      "viewTeamProfiles",
      "manageUsers",
      "managePositions",
      "directory.view",
      "directory.manage",
    ],
    sections: ["staff-roles"],
    defaults: {
      owner: true,
      admin: true,
      manager: true,
      supervisor: false,
      staff: false,
    },
    risk: "medium",
  },
  {
    id: "scheduling",
    label: "Scheduling & Time",
    description: "Shift planning, approvals, and time tracking.",
    icon: CalendarCheck,
    permissions: [
      "viewOwnSchedules",
      "viewTeamSchedules",
      "editSchedules",
      "approveTimeOff",
      "schedule.view",
      "schedule.edit",
    ],
    sections: ["scheduling", "shift-management"],
    defaults: {
      owner: true,
      admin: true,
      manager: true,
      supervisor: true,
      staff: false,
    },
    risk: "medium",
  },
  {
    id: "operations",
    label: "Operations & Inventory",
    description: "Inventory, prep, waste, and purchasing controls.",
    icon: Package,
    permissions: [
      "inventory.view",
      "inventory.create",
      "inventory.edit",
      "inventory.delete",
      "inventory.adjust",
      "inventory.import",
      "inventory.export",
      "inventory.purchasing.view",
      "inventory.purchasing.manage",
      "inventory.counts.view",
      "inventory.counts.create",
      "inventory.counts.edit",
      "inventory.counts.approve",
      "inventory.waste.view",
      "inventory.waste.create",
      "inventory.prep.view",
      "inventory.prep.edit",
      "manageInventory",
    ],
    sections: ["inventory", "cookbook", "production"],
    defaults: {
      owner: true,
      admin: true,
      manager: true,
      supervisor: true,
      staff: false,
    },
    risk: "medium",
  },
  {
    id: "hr",
    label: "HR & Learning",
    description: "Learning center, certifications, and form workflows.",
    icon: GraduationCap,
    permissions: [
      "createForms",
      "manageForms",
      "approveFormSubmissions",
      "approveExpenses",
      "viewOwnProfile",
    ],
    sections: ["learning", "certifications", "recognition"],
    defaults: {
      owner: true,
      admin: true,
      manager: true,
      supervisor: true,
      staff: false,
    },
    risk: "low",
  },
  {
    id: "finance",
    label: "Finance & Billing",
    description: "Expense approvals, billing, and payment access.",
    icon: DollarSign,
    permissions: [
      "viewOwnExpenses",
      "viewTeamExpenses",
      "approveExpenses",
      "managePayments",
      "billing.view",
      "billing.manage",
    ],
    sections: ["expenses"],
    defaults: {
      owner: true,
      admin: true,
      manager: true,
      supervisor: false,
      staff: false,
    },
    risk: "high",
  },
  {
    id: "analytics",
    label: "Analytics & AI Insights",
    description: "Reports, dashboards, and AI-driven recommendations.",
    icon: BarChart3,
    permissions: ["reports.view", "reports.export", "viewAIInsights"],
    sections: ["analytics", "reports"],
    defaults: {
      owner: true,
      admin: true,
      manager: true,
      supervisor: false,
      staff: false,
    },
    risk: "medium",
  },
  {
    id: "system",
    label: "System Administration",
    description: "Critical organization settings and access policies.",
    icon: Settings,
    permissions: [
      "systemSettings",
      "admin.roles",
      "admin.permissions",
      "admin.settings",
    ],
    sections: [],
    defaults: {
      owner: true,
      admin: true,
      manager: false,
      supervisor: false,
      staff: false,
    },
    risk: "high",
  },
];
